# A worflow that installs node on latest ubuntu and show file structure of the repo
name: Tweet-blog-Node-app-action
on: [push]
jobs:
  build-node-app:
    runs-on: ubuntu-latest
    steps:
      # for action -> uses, for shell script -> run
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - run: tree
      - run: pwd
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: Setup finish
        run: echo "Done!"
